import { createContext, ReactNode, useContext, useMemo, useState } from 'react';

export type Language = 'en' | 'am' | 'om';

interface LanguageContextValue {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'layout.subtitle': 'Hermata Merkato Kebele - Jimma, Ethiopia',

    'page.dashboard': 'Vital Events Registration System',
    'page.birth': 'Birth Registration',
    'page.death': 'Death Registration',
    'page.marriage': 'Marriage Registration',
    'page.divorce': 'Divorce Registration',
    'page.search': 'Search Records',
    'page.certificates': 'View Certificate',
    'page.activity': 'Activity & audit log',
    'page.admin': 'Admin',

    'dashboard.hero.tag': 'Digital vital registration',
    'dashboard.hero.ctaPrimary': 'Start new registration',
    'dashboard.hero.ctaNeedAdmin': 'Open Admin to register',
    'dashboard.hero.ctaSecondary': 'Search existing records',
    'dashboard.activity.title': 'Activity overview',
    'dashboard.activity.subtitle': 'Summary of records currently stored in the system.',
    'dashboard.quickActions.title': 'Quick actions',
    'dashboard.quickActions.subtitle': 'Jump directly into the most common tasks.',

    'dashboard.welcomeTitle': 'Welcome to Vital Events Registration System',
    'dashboard.welcomeBody':
      'Select an option below to register vital events, search records, or print certificates.',
    'dashboard.stats.births': 'Births',
    'dashboard.stats.deaths': 'Deaths',
    'dashboard.stats.marriages': 'Marriages',
    'dashboard.stats.divorces': 'Divorces',

    'dashboard.monthly.title': 'This month (by registration date)',
    'dashboard.trends.title': 'Last 6 months',
    'dashboard.trends.subtitle': 'Counts by registration month',
    'dashboard.trends.legend.births': 'Births',
    'dashboard.trends.legend.deaths': 'Deaths',
    'dashboard.trends.legend.marriages': 'Marriages',
    'dashboard.trends.legend.divorces': 'Divorces',
    'dashboard.kebele.title': 'Registrations by kebele',
    'dashboard.deathCauses.title': 'Common causes of death',
    'dashboard.pendingBanner.title': 'Pending approvals',
    'dashboard.pendingBanner.body':
      '{{total}} total pending — Birth: {{b}}, Death: {{d}}, Marriage: {{m}}, Divorce: {{dv}}.',
    'dashboard.pendingBanner.cta': 'Open search (Pending)',

    'dashboard.card.birth.description': 'Register new births and issue birth certificates',
    'dashboard.card.death.description': 'Register deaths and issue death certificates',
    'dashboard.card.marriage.description': 'Register marriages and issue marriage certificates',
    'dashboard.card.divorce.description': 'Register divorces and issue divorce certificates',
    'dashboard.card.search.description': 'Search and view existing vital event records',
    'dashboard.card.certificates.description': 'View and print certificates for issued records',
    'dashboard.card.activity.description': 'See who changed what and when (accountability)',
    'dashboard.card.admin.description': 'Sign in to register records, approve changes, and view the audit log',

    'activity.page.title': 'Audit log',
    'activity.page.subtitle': 'Recent changes to vital records (newest first).',
    'activity.empty': 'No audit entries yet.',
    'activity.column.time': 'Time',
    'activity.column.actor': 'User',
    'activity.column.action': 'Action',
    'activity.column.entity': 'Record',
    'activity.column.details': 'Details',

    'certificate.header.country': 'Federal Democratic Republic of Ethiopia',
    'certificate.header.region': 'Oromia Regional State',
    'certificate.header.office': 'Hermata Merkato Kebele Administration Office',
    'certificate.header.city': 'Jimma, Ethiopia',

    'certificate.birth.title': 'BIRTH CERTIFICATE',
    'certificate.death.title': 'DEATH CERTIFICATE',
    'certificate.marriage.title': 'MARRIAGE CERTIFICATE',
    'certificate.divorce.title': 'DIVORCE CERTIFICATE',

    'certificate.field.registrationNumber': 'Registration Number',
    'certificate.field.childFullName': "Child's Full Name",
    'certificate.field.dateOfBirth': 'Date of Birth',
    'certificate.field.sex': 'Sex',
    'certificate.field.nationality': 'Nationality',
    'certificate.field.motherFullName': "Mother's Full Name",
    'certificate.field.fatherFullName': "Father's Full Name",
    'certificate.field.placeOfBirth': 'Place of Birth',
    'certificate.field.registrationDate': 'Registration Date',

    'certificate.field.fullName': 'Full Name',
    'certificate.field.dateOfDeath': 'Date of Death',
    'certificate.field.causeOfDeath': 'Cause of Death',
    'certificate.field.birthRegNumber': 'Birth Registration Number',
    'certificate.field.lastKnownAddress': 'Last Known Address',

    'certificate.field.husband': 'Husband',
    'certificate.field.wife': 'Wife',
    'certificate.field.age': 'Age',
    'certificate.field.address': 'Address',
    'certificate.field.dateOfMarriage': 'Date of Marriage',
    'certificate.field.dateOfDivorce': 'Date of Divorce',
    'certificate.field.requestedBy': 'Requested By',

    'certificate.footer.issueDate': 'Issue Date',
    'certificate.footer.officialSignature': 'Official Signature',
    'certificate.footer.kebeleAdministrator': 'Kebele Administrator',

    'certificate.actions.print': 'Print Certificate',

    // Forms & search - common
    'common.form.addressSection': 'Address Information',
    'common.form.city': 'City',
    'common.form.kebele': 'Kebele',
    'common.form.houseNumber': 'House Number',
    'common.form.optional': '(optional)',
    'common.form.firstName': 'First name',
    'common.form.middleName': 'Middle name',
    'common.form.lastName': 'Last name',
    'common.form.saveChanges': 'Save changes',
    'common.form.updateSuccess': 'Record updated successfully',

    // Birth registration form
    'birth.form.successTitle': 'Birth Registered Successfully',
    'birth.form.childName': 'Child Full Name',
    'birth.form.dateOfBirth': 'Date of Birth',
    'birth.form.sex': 'Sex',
    'birth.form.nationality': 'Nationality',
    'birth.form.motherName': "Mother Full Name",
    'birth.form.fatherName': "Father Full Name",
    'birth.form.registerButton': 'Register Birth',
    'birth.form.section.child': 'Child (newborn)',
    'birth.form.section.mother': 'Mother',
    'birth.form.section.father': 'Father',
    'birth.form.registrationDate': 'Registration date',

    // Death registration form
    'death.form.successTitle': 'Death Registered Successfully',
    'death.form.fullName': 'Full Name',
    'death.form.birthRegNo': 'Birth Registration Number',
    'death.form.optionalHint': 'Optional: if available',
    'death.form.dateOfBirth': 'Date of Birth',
    'death.form.dateOfDeath': 'Date of Death',
    'death.form.sex': 'Sex',
    'death.form.nationality': 'Nationality',
    'death.form.causeOfDeath': 'Cause of Death',
    'death.form.registerButton': 'Register Death',
    'death.form.section.deceased': 'Deceased',
    'death.form.registrationDate': 'Registration date',

    // Marriage registration form
    'marriage.form.successTitle': 'Marriage Registered Successfully',
    'marriage.form.husbandSection': 'Husband Information',
    'marriage.form.wifeSection': 'Wife Information',
    'marriage.form.fullName': 'Full Name',
    'marriage.form.age': 'Age',
    'marriage.form.nationality': 'Nationality',
    'marriage.form.dateOfMarriage': 'Date of Marriage',
    'marriage.form.registrationDate': 'Registration date',
    'marriage.form.registerButton': 'Register Marriage',

    // Divorce registration form
    'divorce.form.successTitle': 'Divorce Registered Successfully',
    'divorce.form.husbandSection': 'Husband Information',
    'divorce.form.wifeSection': 'Wife Information',
    'divorce.form.fullName': 'Full Name',
    'divorce.form.age': 'Age',
    'divorce.form.nationality': 'Nationality',
    'divorce.form.dateOfDivorce': 'Date of Divorce',
    'divorce.form.requester': 'Requester',
    'divorce.form.requester.husband': 'Husband',
    'divorce.form.requester.wife': 'Wife',
    'divorce.form.requester.mutual': 'Mutual',
    'divorce.form.requester.both': 'Both (legacy)',
    'divorce.form.linkedMarriage': 'Link to marriage record (optional)',
    'divorce.form.linkedMarriage.none': 'None — not linked',
    'divorce.form.registerButton': 'Register Divorce',
    'divorce.form.registrationDate': 'Registration date',

    // Search records
    'search.export.button': 'Download results (CSV)',
    'search.export.summary': '{{count}} row(s) match your current filters (visible tables).',
    'search.form.title': 'Search Records',
    'search.form.placeholder': 'Search by name, registration number...',
    'search.form.status': 'Status',
    'search.form.status.all': 'All statuses',
    'search.form.status.pending': 'Pending',
    'search.form.status.approved': 'Approved',
    'search.form.status.rejected': 'Rejected',
    'search.form.recordType': 'Record Type',
    'search.form.recordType.all': 'All Records',
    'search.form.recordType.birth': 'Birth Records',
    'search.form.recordType.death': 'Death Records',
    'search.form.recordType.marriage': 'Marriage Records',
    'search.form.recordType.divorce': 'Divorce Records',

    'search.form.dateFrom': 'Registration from',
    'search.form.dateTo': 'Registration to',
    'search.form.kebeleFilter': 'Kebele contains',
    'search.form.deathCause': 'Death cause contains',

    'search.person.title': 'Person master (history)',
    'search.person.placeholder': 'Person ID (e.g. P20260001) or name',
    'search.person.lookup': 'Load history',
    'search.person.loading': 'Loading…',
    'search.person.error': 'Could not load person history.',
    'search.person.summary': 'Linked vital records for this person.',
    'search.table.death.title': 'Death Records',
    'search.table.marriage.title': 'Marriage Records',
    'search.table.divorce.title': 'Divorce Records',

    'search.table.column.regNo': 'Reg No.',
    'search.table.column.childName': 'Child Name',
    'search.table.column.dateOfBirth': 'Date of Birth',
    'search.table.column.parents': 'Parents',
    'search.table.column.name': 'Name',
    'search.table.column.dateOfDeath': 'Date of Death',
    'search.table.column.cause': 'Cause',
    'search.table.column.husband': 'Husband',
    'search.table.column.wife': 'Wife',
    'search.table.column.date': 'Date',
    'search.table.column.status': 'Status',
    'search.table.column.actions': 'Actions',
    'search.table.action.viewCertificate': 'View Certificate',
    'search.table.action.editRecord': 'Edit',
    'admin.login.username': 'Email or username',
    'admin.login.password': 'Password',
    'admin.login.submit': 'Sign in',
    'admin.login.close': 'Close',
    'admin.layout.signIn': 'Admin',
    'admin.layout.signOut': 'Sign out',
    'admin.layout.signedInAs': 'Signed in as',
    'admin.page.loginTitle': 'Admin sign-in',
    'admin.page.loginSubtitle':
      'Only an authorized admin account can create or edit vital registrations. Use the credentials configured on the server.',
    'admin.page.hubTitle': 'Admin home',
    'admin.page.signedInAs': 'Signed in as',
    'admin.page.quickActions': 'Registrations & tools',
    'admin.page.backDashboard': 'Back to dashboard',
    'admin.gate.title': 'Admin sign-in required',
    'admin.gate.subtitle':
      'The activity log is available after you sign in on the Admin page with an authorized account.',
    'admin.gate.signInButton': 'Go to Admin page',
    'admin.search.approve': 'Approve',
    'admin.search.reject': 'Reject',
    'admin.error.session': 'Please sign in on the Admin page first.',
    'admin.registerOnly.title': 'Admin access required',
    'admin.registerOnly.body':
      'New vital event registrations can only be submitted by a signed-in admin. Open the Admin page to sign in, then register from there.',
    'admin.registerOnly.cta': 'Open Admin page',
  },
  am: {
    'layout.subtitle': 'ሄርማታ መርካቶ ቀበሌ - ጂማ፣ ኢትዮጵያ',

    'page.dashboard': 'የሕይወት ክስተቶች መመዝገቢያ ስርዓት',
    'page.birth': 'የውለድ መመዝገቢያ',
    'page.death': 'የሞት መመዝገቢያ',
    'page.marriage': 'የጋብቻ መመዝገቢያ',
    'page.divorce': 'የፍቺ መመዝገቢያ',
    'page.search': 'መዝገቦች መፈለጊያ',
    'page.certificates': 'ሰርተፍኬቶች መመልከቻ',
    'page.activity': 'እንቅስቃሴ እና ኦዲት',
    'page.admin': 'አስተዳዳር',

    'dashboard.hero.tag': 'ዲጂታል የሕይወት መመዝገቢያ',
    'dashboard.hero.ctaPrimary': 'አዲስ መመዝገብ ጀምር',
    'dashboard.hero.ctaNeedAdmin': 'ለመመዝገብ አስተዳዳርን ክፈት',
    'dashboard.hero.ctaSecondary': 'የነበሩ መዝገቦችን ፈልግ',
    'dashboard.welcomeTitle': 'ወደ የሕይወት ክስተቶች መመዝገቢያ ስርዓት እንኳን ደህና መጡ',
    'dashboard.welcomeBody':
      'ከሚከተሉት አማራጮች በመምረጥ የሕይወት ክስተቶችን ይመዝግቡ፣ መዝገቦችን ይፈልጉ ወይም ሰርተፍኬቶችን ያትሙ።',
    'dashboard.stats.births': 'ውለዶች',
    'dashboard.stats.deaths': 'ሞቶች',
    'dashboard.stats.marriages': 'ጋብቻዎች',
    'dashboard.stats.divorces': 'ፍቺዎች',

    'dashboard.monthly.title': 'በዚህ ወር (በመመዝገቢያ ቀን)',
    'dashboard.trends.title': 'የመጨረሻዎቹ 6 ወራት',
    'dashboard.trends.subtitle': 'በመመዝገቢያ ወር ብዛት',
    'dashboard.trends.legend.births': 'ውለዶች',
    'dashboard.trends.legend.deaths': 'ሞቶች',
    'dashboard.trends.legend.marriages': 'ጋብቻዎች',
    'dashboard.trends.legend.divorces': 'ፍቺዎች',
    'dashboard.kebele.title': 'በቀበሌ መመዝገቢያዎች',
    'dashboard.deathCauses.title': 'የተለመዱ የሞት ምክንያቶች',
    'dashboard.pendingBanner.title': 'በመጠባበቂያ ላይ ያሉ መዝገቦች',
    'dashboard.pendingBanner.body':
      'ጠቅላላ {{total}} በመጠባበቂያ — ውለድ፦ {{b}}፣ ሞት፦ {{d}}፣ ጋብቻ፦ {{m}}፣ ፍቺ፦ {{dv}}።',
    'dashboard.pendingBanner.cta': 'ፈልግ (በመጠባበቂያ)',

    'dashboard.card.birth.description': 'አዲስ የውለድ መዝገቦችን ይመዝግቡ እና ሰርተፍኬቶች ያውጡ',
    'dashboard.card.death.description': 'የሞት መዝገቦችን ይመዝግቡ እና ሰርተፍኬት ያስገኙ',
    'dashboard.card.marriage.description': 'የጋብቻ መዝገቦችን ይመዝግቡ እና ሰርተፍኬት ያውጡ',
    'dashboard.card.divorce.description': 'የፍቺ መዝገቦችን ይመዝግቡ እና ሰርተፍኬት ያውጡ',
    'dashboard.card.search.description': 'ቀድሞ የተመዘገቡ መዝገቦችን ፈልጉ እና ተመልከቱ',
    'dashboard.card.certificates.description': 'የተሰጡ ሰርተፍኬቶችን ይመልከቱ እና ያትሙ',
    'dashboard.card.activity.description': 'የትኛው ሰው ምን መቼ እንደቀየረ ይመልከቱ (ኃላፊነት)',
    'dashboard.card.admin.description': 'ይግቡ፣ መዝገቦችን ይመዝግቡ፣ ለውጦችን ያጽድቁ እና ኦዲት ይመልከቱ',

    'activity.page.title': 'የኦዲት ምዝግብ',
    'activity.page.subtitle': 'በቅርቡ በሕይወት መዝገቦች ላይ የተደረጉ ለውጦች (አዲሱ በላይ)።',
    'activity.empty': 'እስካሁን የኦዲት ግብዓቶች የሉም።',
    'activity.column.time': 'ጊዜ',
    'activity.column.actor': 'ተጠቃሚ',
    'activity.column.action': 'እርምጃ',
    'activity.column.entity': 'መዝገብ',
    'activity.column.details': 'ዝርዝሮች',

    'certificate.header.country': 'የኢትዮጵያ ፌዴራል ዴሞክራሲያዊ ሪፐብሊክ',
    'certificate.header.region': 'ኦሮሚያ ክልል መንግሥት',
    'certificate.header.office': 'ሄርማታ መርካቶ ቀበሌ አስተዳደር ጽ/ቤት',
    'certificate.header.city': 'ጂማ፣ ኢትዮጵያ',

    'certificate.birth.title': 'የውለድ ሰርተፍኬት',
    'certificate.death.title': 'የሞት ሰርተፍኬት',
    'certificate.marriage.title': 'የጋብቻ ሰርተፍኬት',
    'certificate.divorce.title': 'የፍቺ ሰርተፍኬት',

    'certificate.field.registrationNumber': 'የመመዝገቢያ ቁጥር',
    'certificate.field.childFullName': 'የልጁ ሙሉ ስም',
    'certificate.field.dateOfBirth': 'የውለድ ቀን',
    'certificate.field.sex': 'ፆታ',
    'certificate.field.nationality': 'ዜግነት',
    'certificate.field.motherFullName': 'የእናት ሙሉ ስም',
    'certificate.field.fatherFullName': 'የአባት ሙሉ ስም',
    'certificate.field.placeOfBirth': 'የውለድ ቦታ',
    'certificate.field.registrationDate': 'የመመዝገቢያ ቀን',

    'certificate.field.fullName': 'ሙሉ ስም',
    'certificate.field.dateOfDeath': 'የሞት ቀን',
    'certificate.field.causeOfDeath': 'የሞት ምክንያት',
    'certificate.field.birthRegNumber': 'የውለድ መመዝገቢያ ቁጥር',
    'certificate.field.lastKnownAddress': 'የመጨረሻ የመኖሪያ አድራሻ',

    'certificate.field.husband': 'ሚስት ባል',
    'certificate.field.wife': 'ሚስት',
    'certificate.field.age': 'እድሜ',
    'certificate.field.address': 'አድራሻ',
    'certificate.field.dateOfMarriage': 'የጋብቻ ቀን',
    'certificate.field.dateOfDivorce': 'የፍቺ ቀን',
    'certificate.field.requestedBy': 'ጥያቄ ያቀረበው',

    'certificate.footer.issueDate': 'የሰጠበት ቀን',
    'certificate.footer.officialSignature': 'የመኮንን ፊርማ',
    'certificate.footer.kebeleAdministrator': 'የቀበሌ አስተዳዳሪ',

    'certificate.actions.print': 'ሰርተፍኬት አትም',

    // Forms & search - common
    'common.form.addressSection': 'የአድራሻ መረጃ',
    'common.form.city': 'ከተማ',
    'common.form.kebele': 'ቀበሌ',
    'common.form.houseNumber': 'የቤት ቁጥር',
    'common.form.optional': '(አማራጭ)',
    'common.form.firstName': 'የመጀመሪያ ስም',
    'common.form.middleName': 'የመሃል ስም',
    'common.form.lastName': 'የአባት ስም / የአያት ስም',
    'common.form.saveChanges': 'ለውጦችን አስቀምጥ',
    'common.form.updateSuccess': 'መዝገቡ በተሳካ ሁኔታ ተዘምኗል',

    // Birth registration form
    'birth.form.successTitle': 'የውለድ መመዝገብ ተሳክቷል',
    'birth.form.childName': 'የልጁ ሙሉ ስም',
    'birth.form.dateOfBirth': 'የውለድ ቀን',
    'birth.form.sex': 'ፆታ',
    'birth.form.nationality': 'ዜግነት',
    'birth.form.motherName': 'የእናት ሙሉ ስም',
    'birth.form.fatherName': 'የአባት ሙሉ ስም',
    'birth.form.registerButton': 'ውለድ መዝግብ',
    'birth.form.section.child': 'ልጅ (አዲስ የተወለደ)',
    'birth.form.section.mother': 'እናት',
    'birth.form.section.father': 'አባት',
    'birth.form.registrationDate': 'የመመዝገቢያ ቀን',

    // Death registration form
    'death.form.successTitle': 'የሞት መመዝገብ ተሳክቷል',
    'death.form.fullName': 'ሙሉ ስም',
    'death.form.birthRegNo': 'የውለድ መመዝገቢያ ቁጥር',
    'death.form.optionalHint': '፡ አማራጭ፣ ካለ',
    'death.form.dateOfBirth': 'የውለድ ቀን',
    'death.form.dateOfDeath': 'የሞት ቀን',
    'death.form.sex': 'ፆታ',
    'death.form.nationality': 'ዜግነት',
    'death.form.causeOfDeath': 'የሞት ምክንያት',
    'death.form.registerButton': 'ሞት መዝግብ',
    'death.form.section.deceased': 'የሞተ ሰው',
    'death.form.registrationDate': 'የመመዝገቢያ ቀን',

    // Marriage registration form
    'marriage.form.successTitle': 'የጋብቻ መመዝገብ ተሳክቷል',
    'marriage.form.husbandSection': 'የባል መረጃ',
    'marriage.form.wifeSection': 'የሚስት መረጃ',
    'marriage.form.fullName': 'ሙሉ ስም',
    'marriage.form.age': 'እድሜ',
    'marriage.form.nationality': 'ዜግነት',
    'marriage.form.dateOfMarriage': 'የጋብቻ ቀን',
    'marriage.form.registrationDate': 'የመመዝገቢያ ቀን',
    'marriage.form.registerButton': 'ጋብቻ መዝግብ',

    // Divorce registration form
    'divorce.form.successTitle': 'የፍቺ መመዝገብ ተሳክቷል',
    'divorce.form.husbandSection': 'የባል መረጃ',
    'divorce.form.wifeSection': 'የሚስት መረጃ',
    'divorce.form.fullName': 'ሙሉ ስም',
    'divorce.form.age': 'እድሜ',
    'divorce.form.nationality': 'ዜግነት',
    'divorce.form.dateOfDivorce': 'የፍቺ ቀን',
    'divorce.form.requester': 'ጥያቄ ያቀረበው',
    'divorce.form.requester.husband': 'ባል',
    'divorce.form.requester.wife': 'ሚስት',
    'divorce.form.requester.mutual': 'ጋራ',
    'divorce.form.requester.both': 'ሁለቱም (አሮጌ)',
    'divorce.form.linkedMarriage': 'ወደ የጋብቻ መዝገብ ማገናኘት (አማራጭ)',
    'divorce.form.linkedMarriage.none': 'ምንም — አልተገናኘም',
    'divorce.form.registerButton': 'ፍቺ መዝግብ',
    'divorce.form.registrationDate': 'የመመዝገቢያ ቀን',

    // Search records
    'search.export.button': 'ውጤት አውርድ (CSV)',
    'search.export.summary': 'ከአሁኑ ማጣሪያዎች ጋር የሚዛመዱ {{count}} ተራ(ዎች)።',
    'search.form.title': 'መዝገቦች መፈለጊያ',
    'search.form.placeholder': 'በስም ወይም በመመዝገቢያ ቁጥር ፈልጉ...',
    'search.form.status': 'ሁኔታ',
    'search.form.status.all': 'ሁሉም ሁኔታዎች',
    'search.form.status.pending': 'በመጠባበቂያ',
    'search.form.status.approved': 'ተቀባይነት ያገኘ',
    'search.form.status.rejected': 'ተቀባይነት የሌለው',
    'search.form.recordType': 'የመዝገብ አይነት',
    'search.form.recordType.all': 'ሁሉም መዝገቦች',
    'search.form.recordType.birth': 'የውለድ መዝገቦች',
    'search.form.recordType.death': 'የሞት መዝገቦች',
    'search.form.recordType.marriage': 'የጋብቻ መዝገቦች',
    'search.form.recordType.divorce': 'የፍቺ መዝገቦች',

    'search.form.dateFrom': 'መመዝገቢያ ከ',
    'search.form.dateTo': 'መመዝገቢያ እስከ',
    'search.form.kebeleFilter': 'ቀበሌ ይይዛል',
    'search.form.deathCause': 'የሞት ምክንያት ይይዛል',

    'search.person.title': 'የሰው መሠረታዊ መዝገብ (ታሪክ)',
    'search.person.placeholder': 'የሰው መ.ቁ. (ለምሳሌ P20260001) ወይም ስም',
    'search.person.lookup': 'ታሪክ ጫን',
    'search.person.loading': 'በመጫን ላይ…',
    'search.person.error': 'የሰው ታሪክ መጫን አልተሳካም።',
    'search.person.summary': 'ለዚህ ሰው የተገናኙ የሕይወት መዝገቦች።',
    'search.table.death.title': 'የሞት መዝገቦች',
    'search.table.marriage.title': 'የጋብቻ መዝገቦች',
    'search.table.divorce.title': 'የፍቺ መዝገቦች',

    'search.table.column.regNo': 'መመዝገቢያ ቁ.',
    'search.table.column.childName': 'የልጅ ስም',
    'search.table.column.dateOfBirth': 'የውለድ ቀን',
    'search.table.column.parents': 'ወላጆች',
    'search.table.column.name': 'ስም',
    'search.table.column.dateOfDeath': 'የሞት ቀን',
    'search.table.column.cause': 'ምክንያት',
    'search.table.column.husband': 'ባል',
    'search.table.column.wife': 'ሚስት',
    'search.table.column.date': 'ቀን',
    'search.table.column.status': 'ሁኔታ',
    'search.table.column.actions': 'እርምጃዎች',
    'search.table.action.viewCertificate': 'ሰርተፍኬት ይመልከቱ',
    'search.table.action.editRecord': 'አርም',
    'admin.login.username': 'ኢሜይል ወይም ስም',
    'admin.login.password': 'የይለፍ ቃል',
    'admin.login.submit': 'ግባ',
    'admin.login.close': 'ዝጋ',
    'admin.layout.signIn': 'አስተዳዳር',
    'admin.layout.signOut': 'ውጣ',
    'admin.layout.signedInAs': 'የገባው በስም',
    'admin.page.loginTitle': 'የአስተዳዳር መግቢያ',
    'admin.page.loginSubtitle':
      'የተፈቀዱ የአስተዳዳር መለያዎች ብቻ አዲስ መመዝገብ ሊያደርጉ ይችላሉ። በሰርቨር ላይ የተዋቀሩትን መረጃ ይጠቀሙ።',
    'admin.page.hubTitle': 'የአስተዳዳር መነሻ',
    'admin.page.signedInAs': 'የገባው በስም',
    'admin.page.quickActions': 'መመዝገብ እና መሳሪያዎች',
    'admin.page.backDashboard': 'ወደ ዳሽቦርድ ተመለስ',
    'admin.gate.title': 'የአስተዳዳር መግቢያ ያስፈልጋል',
    'admin.gate.subtitle':
      'የኦዲት ምዝገብ ከአስተዳዳር ገፅ በተፈቀደ መለያ ከመግባት በኋላ ይገኛል።',
    'admin.gate.signInButton': 'ወደ አስተዳዳር ገፅ ሂድ',
    'admin.search.approve': 'አጽድቅ',
    'admin.search.reject': 'አትቀበል',
    'admin.error.session': 'እባክዎ በመጀመሪያ በአስተዳዳር ገፅ ይግቡ።',
    'admin.registerOnly.title': 'የአስተዳዳር መዳረሻ ያስፈልጋል',
    'admin.registerOnly.body':
      'አዲስ የሕይወት መዝገብ በገባ አስተዳዳር ብቻ ይላካል። በአስተዳዳር ገፅ ይግቡ፣ ከዚያ ይመዝግቡ።',
    'admin.registerOnly.cta': 'አስተዳዳር ገፅ ክፈት',
  },
  om: {
    'layout.subtitle': 'Kebele Hermata Merkato - Jimmaa, Itiyoophiyaa',

    'page.dashboard': "Sirna Galmeessa Taateewwan Jireenyaa",
    'page.birth': 'Galmeessa Dhalootaa',
    'page.death': 'Galmeessa Du\'aa',
    'page.marriage': 'Galmeessa Fuudhaafi Heerumaa',
    'page.divorce': 'Galmeessa Divorsii',
    'page.search': 'Galmeewwan barbaadi',
    'page.certificates': 'Ejjannoo daawwachuu',
    'page.activity': 'Sochii fi galmaa hojii',
    'page.admin': 'Admiinii',

    'dashboard.hero.tag': 'Galmeessa diijiitaalaa taateewwan jireenyaa',
    'dashboard.hero.ctaPrimary': 'Galmeessa haaraa jalqabi',
    'dashboard.hero.ctaNeedAdmin': 'Galmeessuuf fuula admiinii bani',
    'dashboard.hero.ctaSecondary': 'Galmeewwan jiran barbaadi',
    'dashboard.welcomeTitle': 'Baga gara sirna galmeessa taateewwan jireenyaa dhuftan',
    'dashboard.welcomeBody':
      'Filannoo armaan gadii keessaa filadhaan taateewwan galmeessi, galmeewwan barbaadi yookaan ejjannoo maxxansi.',
    'dashboard.stats.births': 'Dhaloonni',
    'dashboard.stats.deaths': 'Du\'oonni',
    'dashboard.stats.marriages': 'Fuudhaaf Heerumni',
    'dashboard.stats.divorces': 'Divorsiin',

    'dashboard.monthly.title': 'Ji’a kana (guyyaa galmaa irratti hundaa\'e)',
    'dashboard.trends.title': 'Ji’oota 6 darban',
    'dashboard.trends.subtitle': 'Lakkoofsa ji’a galmaa irratti',
    'dashboard.trends.legend.births': 'Dhaloonni',
    'dashboard.trends.legend.deaths': 'Du\'oonni',
    'dashboard.trends.legend.marriages': 'Fuudhaaf heerumni',
    'dashboard.trends.legend.divorces': 'Divorsiin',
    'dashboard.kebele.title': 'Galmeewwan kebeleetti',
    'dashboard.deathCauses.title': 'Sababaan du\'aa beekamaa',
    'dashboard.pendingBanner.title': 'Galmeewwan mirkanaa\'uu eegaman',
    'dashboard.pendingBanner.body':
      'Waliigala {{total}} eegamaa jira — Dhaloota: {{b}}, Du\'aa: {{d}}, Fuudhaafi heeruma: {{m}}, Divorsii: {{dv}}.',
    'dashboard.pendingBanner.cta': 'Barbaacha bani (Eegamaa)',

    'dashboard.card.birth.description': 'Dhaloota haaraa galmeessi fi ejjannoo kenni',
    'dashboard.card.death.description': 'Du\'a galmeessi fi ejjannoo du\'aa kenni',
    'dashboard.card.marriage.description': 'Fuudhaa fi heeruma galmeessi fi ejjannoo kenni',
    'dashboard.card.divorce.description': 'Divorsii galmeessi fi ejjannoo kenni',
    'dashboard.card.search.description': 'Galmeewwan duraan jiran barbaadi fi daawwadhu',
    'dashboard.card.certificates.description': 'Ejjannoo kenname daawwadhu fi maxxansi',
    'dashboard.card.activity.description': 'Eenyu maal yeroo kamitti jijjiire akka jiru ilaali (itti gaafatamummaa)',
    'dashboard.card.admin.description': 'Seeni, galmeewwan galmeessi, jijjiirama mirkaneessi fi galmaa hojii ilaali',

    'activity.page.title': 'Galmaa hojii',
    'activity.page.subtitle': 'Jijjiirama dhiyoo galmeewwan jireenyaa irratti (haaraan duratti).',
    'activity.empty': 'Galmaa hojii ammallee hin jiru.',
    'activity.column.time': 'Yeroo',
    'activity.column.actor': 'Fayyadamaa',
    'activity.column.action': 'Gocha',
    'activity.column.entity': 'Galmee',
    'activity.column.details': 'Ibsa',

    'certificate.header.country': 'Rippabiliika Dimokraatawaa Federaalaa Itiyoophiyaa',
    'certificate.header.region': 'Naannoo Oromiyaa',
    'certificate.header.office': 'Biiroo Bulchiinsa Kebele Hermata Merkato',
    'certificate.header.city': 'Jimmaa, Itiyoophiyaa',

    'certificate.birth.title': 'EJJANNOO DHALOOTAA',
    'certificate.death.title': 'EJJANNOO DU\'AA',
    'certificate.marriage.title': 'EJJANNOO FUUDHAAFI HEERUMAA',
    'certificate.divorce.title': 'EJJANNOO DIVORSII',

    'certificate.field.registrationNumber': 'Lakkoofsa Galmee',
    'certificate.field.childFullName': 'Maqaa guutuu daa\'immaa',
    'certificate.field.dateOfBirth': 'Guyyaa dhalootaa',
    'certificate.field.sex': 'Saala',
    'certificate.field.nationality': 'Biyya abbaa',
    'certificate.field.motherFullName': 'Maqaa guutuu haadha',
    'certificate.field.fatherFullName': 'Maqaa guutuu abbaa',
    'certificate.field.placeOfBirth': 'Bakka dhalootaa',
    'certificate.field.registrationDate': 'Guyyaa galmee',

    'certificate.field.fullName': 'Maqaa guutuu',
    'certificate.field.dateOfDeath': 'Guyyaa du\'aa',
    'certificate.field.causeOfDeath': 'Sababaa du\'aa',
    'certificate.field.birthRegNumber': 'Lakkoofsa galmee dhalootaa',
    'certificate.field.lastKnownAddress': 'Teessoo dhumaa beekamu',

    'certificate.field.husband': 'Abbaa warraa',
    'certificate.field.wife': 'Haadha warraa',
    'certificate.field.age': 'Umrii',
    'certificate.field.address': 'Teessoo',
    'certificate.field.dateOfMarriage': 'Guyyaa fuudhaa fi heerumaa',
    'certificate.field.dateOfDivorce': 'Guyyaa divorsii',
    'certificate.field.requestedBy': 'Kan gaafate',

    'certificate.footer.issueDate': 'Guyyaa bahe',
    'certificate.footer.officialSignature': 'Mallattoo aangooftuu',
    'certificate.footer.kebeleAdministrator': 'Bulchaa Kebelee',

    'certificate.actions.print': 'Ejjannoo maxxansi',

    // Forms & search - common
    'common.form.addressSection': 'Odeeffannoo Teessoo',
    'common.form.city': 'Magaalaa',
    'common.form.kebele': 'Kebele',
    'common.form.houseNumber': 'Lakkoofsa Manaa',
    'common.form.optional': '(filannoo)',
    'common.form.firstName': 'Maqaa jalqabaa',
    'common.form.middleName': 'Maqaa gidduu',
    'common.form.lastName': 'Maqaa xumuraa',
    'common.form.saveChanges': 'Jijjiirama ol\'a\'i',
    'common.form.updateSuccess': 'Galmee milkaa\'inaan ol\'e\'ame',

    // Birth registration form
    'birth.form.successTitle': 'Galmeessi dhalootaa milkaaʼe',
    'birth.form.childName': 'Maqaa guutuu daa\'immaa',
    'birth.form.dateOfBirth': 'Guyyaa dhalootaa',
    'birth.form.sex': 'Saala',
    'birth.form.nationality': 'Biyya abbaa',
    'birth.form.motherName': 'Maqaa guutuu haadha',
    'birth.form.fatherName': 'Maqaa guutuu abbaa',
    'birth.form.registerButton': 'Dhaloota galmeessi',
    'birth.form.section.child': 'Daa\'immaa (haaraa dhalate)',
    'birth.form.section.mother': 'Haadha',
    'birth.form.section.father': 'Abbaa',
    'birth.form.registrationDate': 'Guyyaa galmee',

    // Death registration form
    'death.form.successTitle': 'Galmeessi du\'aa milkaaʼe',
    'death.form.fullName': 'Maqaa guutuu',
    'death.form.birthRegNo': 'Lakkoofsa galmee dhalootaa',
    'death.form.optionalHint': 'Hanga danda’ame yoo jiraate',
    'death.form.dateOfBirth': 'Guyyaa dhalootaa',
    'death.form.dateOfDeath': 'Guyyaa du\'aa',
    'death.form.sex': 'Saala',
    'death.form.nationality': 'Biyya abbaa',
    'death.form.causeOfDeath': 'Sababaa du\'aa',
    'death.form.registerButton': 'Du\'a galmeessi',
    'death.form.section.deceased': 'Kan du\'e',
    'death.form.registrationDate': 'Guyyaa galmee',

    // Marriage registration form
    'marriage.form.successTitle': 'Galmeessi fuudhaa fi heerumaa milkaaʼe',
    'marriage.form.husbandSection': 'Odeeffannoo abbaa warraa',
    'marriage.form.wifeSection': 'Odeeffannoo haadha warraa',
    'marriage.form.fullName': 'Maqaa guutuu',
    'marriage.form.age': 'Umrii',
    'marriage.form.nationality': 'Biyya abbaa',
    'marriage.form.dateOfMarriage': 'Guyyaa fuudhaa fi heerumaa',
    'marriage.form.registrationDate': 'Guyyaa galmee',
    'marriage.form.registerButton': 'Fuudhaa fi heeruma galmeessi',

    // Divorce registration form
    'divorce.form.successTitle': 'Galmeessi divorsii milkaaʼe',
    'divorce.form.husbandSection': 'Odeeffannoo abbaa warraa',
    'divorce.form.wifeSection': 'Odeeffannoo haadha warraa',
    'divorce.form.fullName': 'Maqaa guutuu',
    'divorce.form.age': 'Umrii',
    'divorce.form.nationality': 'Biyya abbaa',
    'divorce.form.dateOfDivorce': 'Guyyaa divorsii',
    'divorce.form.requester': 'Kan gaafate',
    'divorce.form.requester.husband': 'Abbaa warraa',
    'divorce.form.requester.wife': 'Haadha warraa',
    'divorce.form.requester.mutual': 'Waliigaltee',
    'divorce.form.requester.both': 'Lamaan isaanii (duraanii)',
    'divorce.form.linkedMarriage': 'Galmee fuudhaa fi heerumaa waliin walitti hidhi (filannoo)',
    'divorce.form.linkedMarriage.none': 'Homaa — hin walitti hidhamne',
    'divorce.form.registerButton': 'Divorsii galmeessi',
    'divorce.form.registrationDate': 'Guyyaa galmee',

    // Search records
    'search.export.button': 'Bu\'aa buusu (CSV)',
    'search.export.summary': 'Filannoo ammaa waliin walitti dhufan safaroota {{count}}.',
    'search.form.title': 'Galmeewwan barbaadi',
    'search.form.placeholder': 'Maqaa yookaan lakkoofsa galmee fayyadami...',
    'search.form.status': 'Haala',
    'search.form.status.all': 'Haala mara',
    'search.form.status.pending': 'Eegamaa jira',
    'search.form.status.approved': 'Mirmeessame',
    'search.form.status.rejected': 'Hafame',
    'search.form.recordType': 'Gosa galmee',
    'search.form.recordType.all': 'Galmeewwan hundaa',
    'search.form.recordType.birth': 'Galmeewwan dhalootaa',
    'search.form.recordType.death': 'Galmeewwan du\'aa',
    'search.form.recordType.marriage': 'Galmeewwan fuudhaa fi heerumaa',
    'search.form.recordType.divorce': 'Galmeewwan divorsii',

    'search.form.dateFrom': 'Galmaa irraa',
    'search.form.dateTo': 'Galmaa hanga',
    'search.form.kebeleFilter': 'Kebeleen qaba',
    'search.form.deathCause': 'Sababni du\'aa qaba',

    'search.person.title': 'Galmaa namaa (seenaa)',
    'search.person.placeholder': 'ID namaa (fakkaataa P20260001) ykn maqaa',
    'search.person.lookup': 'Seenaa fe\'i',
    'search.person.loading': 'Fe\'amaa jira…',
    'search.person.error': 'Seenaa namaa fe\'uun hin milkoofne.',
    'search.person.summary': 'Galmeewwan jireenyaa nama kanaaf walitti hidhaman.',
    'search.table.death.title': 'Galmeewwan du\'aa',
    'search.table.marriage.title': 'Galmeewwan fuudhaa fi heerumaa',
    'search.table.divorce.title': 'Galmeewwan divorsii',

    'search.table.column.regNo': 'Lakkoofsa galmee',
    'search.table.column.childName': 'Maqaa daa\'immaa',
    'search.table.column.dateOfBirth': 'Guyyaa dhalootaa',
    'search.table.column.parents': 'Maatii',
    'search.table.column.name': 'Maqaa',
    'search.table.column.dateOfDeath': 'Guyyaa du\'aa',
    'search.table.column.cause': 'Sababaa',
    'search.table.column.husband': 'Abbaa warraa',
    'search.table.column.wife': 'Haadha warraa',
    'search.table.column.date': 'Guyyaa',
    'search.table.column.status': 'Haala',
    'search.table.column.actions': 'Gochoota',
    'search.table.action.viewCertificate': 'Ejjannoo daawwadhu',
    'search.table.action.editRecord': 'Gulaali',
    'admin.login.username': 'Imeelii ykn maqaa',
    'admin.login.password': 'Jeecha iccitii',
    'admin.login.submit': 'Seeni',
    'admin.login.close': 'Cufi',
    'admin.layout.signIn': 'Admiinii',
    'admin.layout.signOut': 'Ba\'i',
    'admin.layout.signedInAs': 'Seenan maqaa',
    'admin.page.loginTitle': 'Seensa admiinii',
    'admin.page.loginSubtitle':
      'Galmeessa taateewwan haaraa qofa fayyadamaa admiinii hayyamameen ta\'uu danda\'a. Odeeffannoo serveeritti qopheeffame fayyadami.',
    'admin.page.hubTitle': 'Mana admiinii',
    'admin.page.signedInAs': 'Seenan maqaa',
    'admin.page.quickActions': 'Galmeessuu fi meeshaalee',
    'admin.page.backDashboard': 'Gara daashboordii deebi\'i',
    'admin.gate.title': 'Seensa admiinii barbaachisa',
    'admin.gate.subtitle':
      'Galmaa hojii fuula admiinii irratti fayyadamaa hayyamameen seenee booda argama.',
    'admin.gate.signInButton': 'Gara fuula admiinii deemii',
    'admin.search.approve': 'Mirkaneessi',
    'admin.search.reject': 'Diduu',
    'admin.error.session': 'Dura fuula admiinii irratti seenaa.',
    'admin.registerOnly.title': 'Seensa admiinii barbaachisa',
    'admin.registerOnly.body':
      'Galmeessa taateewwan jireenyaa haaraa qofa admiinii seenan erguu danda\'a. Fuula admiinii irratti seenaa, sana booda galmeessi.',
    'admin.registerOnly.cta': 'Fuula admiinii bani',
  },
};

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const value = useMemo(
    () => ({
      language,
      setLanguage,
      t: (key: string) => translations[language][key] ?? translations.en[key] ?? key,
    }),
    [language]
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return ctx;
}

